#
# A simple Layout
#
class SimpleLayout < Cuca::Layout
 def output
    content << <<-EOF 
<HTML>
   <HEAD><TITLE>Cuca Default Page - #{@page_title}</TITLE></HEAD>
   <LINK href="/css/style.css" type="text/css" rel="stylesheet"></LINK>
     
   <BODY>
     #{@content_for_layout}
     <HR/>
     <SMALL>Generated by Cuca Framework #{Time.now} (using 'simple' demo layout on Cuca Version #{Cuca::VERSION} on Ruby #{RUBY_VERSION})</SMALL>
   </BODY>
</HTML>
    EOF
 end
end
